export const metadata = {
  title: "Status",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <h1>this is status</h1>
        </div>
    );
};

export default page;