export const metadata = {
  title: "Timeline",
  description: "Generated by create next app",
};

const page = () => {
    return (
        <div>
            <h2>this is timeline</h2>
        </div>
    );
};

export default page;